const { CALLER_NAME } = require("./config");

const OBJECTION_LIBRARY = [
  {
    id: "what_is_this",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "what is this",
      "what is this about",
      "what is this regarding",
      "what are you calling about",
      "what is this in reference to",
      "what do you want",
      "what do you need",
      "what is this concerning",
      "what is this supposed to be",
      "what are we talking about",
      "what is this call regarding",
      "what is the reason for the call",
      "what's going on",
      "what is this about exactly",
      "why are you calling",
      "what are you trying to do",
      "what is this all about",
      "what's this about again",
      "why did you call me",
      "what is this for",
    ],
    response: [
      "Yea, this is just about the mortgage protection file tied to the home.",
      "[PAUSE_3_SECONDS]",
      "From what I'm seeing, it never got fully reviewed on my end.",
    ],
  },
  {
    id: "how_did_you_get_my_info",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "how did you get my info",
      "how did you get my information",
      "where did you get my info",
      "where did you get my information",
      "how did you get my number",
      "how do you have my number",
      "how did you find me",
      "where did you get this",
      "where did you get my contact info",
      "how did yall get my info",
      "why do you have my information",
      "where are you pulling this from",
      "who gave you my number",
      "how did you get ahold of me",
      "why do you have my number",
      "where did this come from",
      "how are you connected to me",
      "who gave you my information",
      "where did yall get my number",
      "how did you get this number",
    ],
    response: [
      "From what I'm seeing here, it was tied to the mortgage file from when the home was closed, and I'm just the case worker assigned to review it on my end.",
    ],
  },
  {
    id: "is_this_a_scam",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "is this a scam",
      "this sounds like a scam",
      "are you a scam",
      "sounds like a scam",
      "is this legit",
      "is this real",
      "how do i know this is real",
      "how do i know this is legit",
      "you sound fake",
      "this doesnt sound real",
      "this doesn't sound real",
    ],
    response: [
      "No, I get why you'd ask. I'm just calling about the mortgage protection file tied to the home, and my job is to verify the information and get you scheduled if you want to review it.",
    ],
  },
  {
    id: "cost",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "how much does this cost",
      "how much is it",
      "what does it cost",
      "what is the cost",
      "the cost",
      "price",
      "pricing",
      "too expensive",
      "how much",
      "what's the price",
      "premium",
      "how much per month",
      "monthly premium",
      "monthly payment",
    ],
    response: [
      "Totally fair...",
      "That’s actually why we set it up this way — the underwriter works with a bunch of A-rated companies,",
      "so he can find whatever the most affordable option is for you.",
      "And since the call’s free, worst case you just get clarity on your options and decide from there.",
    ],
  },
  {
    id: "mandatory",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "is this mandatory",
      "is this required",
      "do i have to do this",
      "do i need to do this",
      "do i have to have this",
      "is this required for the mortgage",
      "is this necessary",
    ],
    response: [
      "No, not at all. I'm just following up on the request that was sent in so that way the underwriter can go over those options with you.",
    ],
  },
  {
    id: "who_do_you_work_for",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "who do you work for",
      "who are you with",
      "what company are you with",
      "what company do you work for",
      "who do you represent",
      "where are you calling from",
      "what company is this",
      "what company are you calling from",
      "who are you calling with",
      "what office are you with",
      "what organization are you with",
      "who is your company",
      "what is the name of your company",
      "what company do you represent",
      "what agency are you with",
      "who do you work with",
    ],
    response: [
      "I work with the underwriter assigned to the file. He is contracted with multiple carrier's within the state, so we aren't tied to just one company.",
    ],
  },
  {
    id: "email_it",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "can you just email it to me",
      "just email it to me",
      "email it to me",
      "send me something",
      "send it to me",
      "email me the info",
      "can you text it to me",
      "just text me",
      "send it over",
    ],
    response: [
      "I wish I could, that would make my job a lot easier, but the actual options depend on your age, health, and what you need, which is why we set the review with the underwriter.",
    ],
  },
  {
    id: "are_you_selling",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "are you trying to sell me something",
      "are you selling me insurance",
      "is this a sales call",
      "are you selling something",
      "is this some kind of sales call",
      "are you pitching me something",
      "is this a solicitation",
    ],
    response: [
      "No, I'm not trying to sell you anything. My job is just to verify the file and get you appointed with the underwriter. Mortgage protection is something you have to apply for, it can't just be bought off the shelf, like a loaf of bread.",
    ],
  },
  {
    id: "call_back",
    category: "recoverable",
    action: "callback_branch",
    triggers: [
      "can you call me back",
      "call me back",
      "i'll call you back",
      "call me later",
      "can we do this later",
      "can we talk later",
      "i'm busy",
      "im busy",
      "i can't talk right now",
      "i cant talk right now",
      "not a good time",
      "this is a bad time",
      "i'm at work",
      "im at work",
      "give me a call later",
    ],
    response: [
      "Yea, of course. No decisions are being made on this call. I just need to find a time that works best for you to speak with the underwriter.",
    ],
  },
  {
    id: "who_are_you",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "who are you",
      "what's your name",
      "what is your name",
      "who is this",
      "who am i speaking with",
      "what was your name",
      "say your name again",
      "who's this",
    ],
    response: [
      `Of course, this is ${CALLER_NAME}. I'm the case worker assigned to your mortgage protection file on my end.`,
    ],
  },
  {
    id: "qualify",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "i don't think i'd qualify",
      "i dont think id qualify",
      "would i qualify",
      "qualify",
      "qualification",
      "would i even qualify",
      "i probably wouldn't qualify",
      "not sure if i qualify",
      "would i be approved",
    ],
    response: [
      "I completely understand...",
      "That’s exactly why I’m calling — the underwriter works with multiple A-rated carriers,",
      "so he can usually find something that fits based on your age and health.",
    ],
  },
  {
    id: "no_mortgage",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "i don't have a mortgage",
      "i dont have a mortgage",
      "my house is paid off",
      "my home is paid off",
      "house is paid off",
      "home is paid off",
      "i paid it off",
      "it's paid off",
      "its paid off",
      "mortgage is paid off",
      "there is no mortgage",
      "i own it outright",
    ],
    response: [
      "Okay, no worries let me just update your file here... Now, mortgage protection is something that follows you specifically. So in the event that you no longer have a mortgage, you would still be covered if something were to happen to you. Whether that be income replacement, or final expenses.",
    ],
  },
  {
    id: "not_interested",
    category: "recoverable",
    action: "branch_followup",
    triggers: [
      "i'm not interested",
      "im not interested",
      "not interested",
      "no thanks",
      "i'm good",
      "im good",
      "i do not want it",
      "i dont want it",
      "don't want it",
      "i'm all set",
      "im all set",
      "not really interested",
      "not for me",
      "i'm fine",
      "im fine",
      "i dont need it",
      "i don't need it",
      "i'm not looking for anything",
      "im not looking for anything",
      "no thank you",
      "i'll pass",
    ],
    response: [
      "Gotcha...",
      "just so I handle the file correctly — is that more because of cost,",
      "or you're not sure you'd qualify?",
    ],
  },
  {
    id: "already_have_insurance",
    category: "recoverable",
    action: "existing_coverage_branch",
    triggers: [
      "i already have insurance",
      "i already have life insurance",
      "i already have coverage",
      "im already covered",
      "i have a policy already",
      "i already have a policy in place",
      "im taken care of",
      "im already protected",
      "i already got that",
      "ive already got something",
      "i already have coverage for that",
      "im set",
      "i already handled that a while ago",
      "i have enough insurance",
      "i have it through work",
      "i have insurance through my job",
      "i already have life insurance through my job",
      "i already have something for that",
      "i already took care of that",
      "i'm good on that",
    ],
    response: [
      "Okay great. Is that a personal policy, something through work, or something specifically set up for the mortgage?",
    ],
  },
  {
    id: "never_filled_anything_out",
    category: "recoverable",
    action: "resume_script_next_step",
    triggers: [
      "i never filled anything out",
      "i never filled that out",
      "i didn't fill anything out",
      "i did not fill anything out",
      "i don't remember filling that out",
      "i dont remember filling that out",
      "i don't remember that",
      "i dont remember that",
      "i don't remember doing that",
      "i dont remember doing that",
      "i don't recall filling this out",
      "i dont recall filling this out",
      "i never requested that",
      "i never asked for that",
      "i don't remember applying",
      "i dont remember applying",
      "i never applied for that",
      "i didnt apply for that",
      "i never signed up for that",
    ],
    response: [
      "No worries, most people don't remember right away, especially if it's been a while. I'm just reaching back out to make sure the file got handled correctly.",
    ],
  },
  {
    id: "do_not_call",
    category: "terminal",
    action: "end_call",
    triggers: [
      "stop calling me",
      "take me off your call list",
      "remove me from your list",
      "don't call me again",
      "dont call me again",
      "do not call me again",
      "quit calling me",
      "put me on do not call",
      "take me off the list",
      "remove me",
      "stop calling",
      "leave me alone",
      "take me off",
      "put me on the do not call list",
    ],
    response: [
      "Oh okay, sorry about that. I'll go ahead and close this out for you. Have a great day.",
    ],
  },
];

module.exports = {
  OBJECTION_LIBRARY,
};
